drop bionic support
canonical/charm-apt-mirror pull request #27
Opened 2024-01-08 16:08 UTC by rgildein

The functional tests are failing for Bionic series, and since we do not need to support it anymore.

2024-01-08 17:11 UTC, sudeephb approved these changes

2024-01-08 17:15 UTC, agileshaw requested changes
Now that we no longer support bionic, we should un-pin `ops` in `requirements.txt` and update README (which contains an example of bionic deployment).

2024-01-08 17:24 UTC, aieri approved these changes

2024-01-09 14:54 UTC, rgildein commented
> Now that we no longer support bionic, we should un-pin `ops` in `requirements.txt` and update README (which contains an example of bionic deployment).

Thanks, I removed any mention of Bionic (from examples, tests and default values).

2024-01-09 15:02 UTC, agileshaw reviewed
Just one small change suggested inline, otherwise looks good.

2024-01-09 15:02 UTC, agileshaw commented on tests/functional/test_charm.py
>          # focal.
```suggestion
        # Let's switch back to Focal and create a snapshot before switching to
        # jammy.
```

2024-01-09 18:09 UTC, agileshaw approved these changes
LGTM, thanks

2024-01-09 18:19 UTC, merged